### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-silviademiguel7#1]
Really cool job @silviademiguel7  !!!

Here you have some tips to improve the exercise:

- [ ] Fix the language of the page
- [ ] Be extra careful with syntax, the Header element should appear before the Main tag
- [ ] We need a nav and an h1 tags
- [ ] Menu items should be clickable and have an HREF attribute
- [ ] Humanize text in `alt` attributes, a sentence without the dash `-` may do the trick ;).
- [ ] Move the font CSS link before your main CSS
- [ ] Class selectors are free, let's use them instead tag selectors 
- [ ] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [ ] Finish the main title styles: font-size ;)

Once you have these fixed try to finish the styles.

Let me know if you have any doubts ;)

Go for it!!

**Comment by silviademiguel7** [comment]
already it is fixed
